var util= require('util');
const utf8Encoder = new TextEncoder();


var _0x4536c5 = [
    "Safari",
    "removeEventListener",
    "MetaSr",
    "A[href*=\"http://interactive.forthnet.gr/click?\"]",
    "rest",
    "Netscape",
    "Vrinda",
    "a[href*=\"//febrare.ru/\"]",
    ".zergnet-recommend",
    "superclass",
    "index",
    ".youtube-social",
    "write",
    "Symbian",
    "-----END RSA PRIVATE KEY-----",
    "seq",
    "\n  ",
    "div[class^=\"app_gdpr\"]",
    "Adr",
    "DERInteger",
    "div[id^=\"crt-\"][data-criteo-id]",
    "a[href^=\"/magazin/\"]",
    "notifications",
    "setByInteger",
    "screen",
    "getFreshValueHex",
    "_values",
    "clone",
    "BlackBerry",
    "span",
    "YAHOO.lang.extend failed, please check that all dependencies are included.",
    "vendor",
    "[object Blob]",
    "cos",
    "responseTextAccessorGet",
    "hpwOS",
    "malformed oid string: ",
    "remainder",
    "join",
    "subtract",
    "key",
    "1px",
    "revert",
    "9.5",
    "#taotaole",
    "CSSMozDocumentRule",
    "pop",
    "knee",
    "a[href^=\"//telegram.me/share/url?\"]",
    "hash",
    "timeZone",
    "parseTime",
    "msSetImmediate",
    "a[href*=\"://chikidiki.ru\"]",
    "SimHei",
    "log",
    "WebOS",
    "[object String]",
    "availTop",
    "a[href=\"http://www.salidzini.lv/\"][style=\"display: block; width: 88px; height: 31px; overflow: hidden; position: relative;\"]",
    ".BlockNag__Card",
    "select-multiple",
    "Gill Sans",
    "stringify",
    "Expected the arguments to be of type `string`",
    "timestamp",
    "like Mac OS X",
    "dMultiply",
    "clear",
    "mpl",
    "converter",
    "hasPublicKeyProperty",
    "ftp",
    "getLowestSetBit",
    "pick",
    "empty",
    "comma",
    "Sogou",
    "null",
    "BatteryManager",
    "BankGothic Md BT",
    "qmze1yzvhyzcyyjr",
    "slashes",
    "assign",
    "signum",
    "mousemove",
    "Pristina",
    "maxTouchPoints",
    "MediaSettingsRange",
    "DERBitString",
    "DingTalk",
    "click",
    "debug",
    "ONE",
    "exclude",
    "toPrettyString",
    "#mgid_iframe",
    "[id^=\"sklikReklama\"]",
    "toLowerCase",
    "parseKey",
    "GeneralString",
    "Arial Unicode MS",
    "trys",
    "getTimezoneOffset",
    "connect",
    "round",
    "#AD_banner_bottom",
    "[href^=\"https://zbet.vn/\"]",
    ".img-kosana",
    "480",
    "formatDate",
    "[title=\"ALIENBOLA\" i]",
    "a[href^=\"http://advmanager.techfun.pl/redirect/\"]",
    "multiplyUpperTo",
    "mmMwWLliI0O&1",
    "clearBit",
    "Meiryo UI",
    "Windows",
    "a[href^=\"http://adserv.ontek.com.tr/\"]",
    "prototype",
    "getPrivateBaseKeyB64",
    "timeout",
    ".bumq",
    "iPhone",
    "copyTo",
    "ul.adsmodern",
    "response",
    "head",
    "DERSequence",
    ".geminiLB1Ad",
    "content",
    "CSSPrimitiveValue",
    "integerToByteHex",
    "compareTo",
    "sqrTo",
    "absolute",
    "matches",
    "trim",
    "8.1",
    "3041300d060960864801650304020205000430",
    "responseXML",
    "toByteArray",
    "(min-monochrome: 0)",
    "isExplicit",
    "obfuscator",
    "square",
    "hasPrivateKeyProperty",
    "languages",
    "Vivaldi",
    "Unrecognized time: ",
    "return this",
    "zoom",
    "Invalid RSA public key",
    "disconnect",
    "shiftRight",
    "#reklamni-box",
    "parseFragmentIdentifier",
    "toUTCString",
    "exception",
    "toString",
    "getPrivateKey",
    "mulTo",
    "baiduboxapp",
    "Huawei",
    "[object Intl]",
    "ins.daum_ddn_area",
    "ASN1Object",
    " (encapsulates)",
    "high",
    "split",
    "some",
    "ENUMERATED",
    "squareTo",
    "default_key_size",
    "Taobao",
    "MSIE",
    "return",
    "Monotype Corsiva",
    "2HFyoQv",
    "ontransitioncancel",
    "a[href^=\"http://g1.v.fwmrm.net/ad/\"]",
    "Yandex",
    "checkbox",
    "A[href*=\"adman.otenet.gr/click?\"]",
    "Chrome",
    "HONOR",
    "table",
    "getTime",
    "(-webkit-min-device-pixel-ratio: 2), (min-device-pixel-ratio: 2), (min-resolution: 192dpi)",
    "unicode-1-1-utf-8",
    "#backkapat",
    "parseOID",
    "indexedDB",
    "IqiyiApp",
    "getKey",
    ".wp_adblock_detect",
    "setByBigInteger",
    "rtt",
    "lastIndexOf",
    "webkitTemporaryStorage",
    "Ubuntu",
    "a[href*=\"doktor-se.onelink.me\"]",
    ".ylamainos",
    "QihooBrowser",
    "generateAsync",
    "/cutntllmtlhyjnim",
    "div[class$=\"-hide\"][zoompage-fontsize][style=\"display: block;\"]",
    "0123456789ABCDEF",
    "gen",
    "floor",
    "tagClass",
    "IEMobile",
    "lang",
    "Gecko/",
    "port",
    "(((.+)+)+)+$",
    "asn1Array",
    "a[href^=\"http://izlenzi.com/campaign/\"]",
    "querySelector",
    "Futura Md BT",
    "one_time_token",
    "fromRadix",
    "position",
    "symbol",
    "utc",
    "a[href^=\"https://l.profitshare.ro/\"]",
    "Konqueror",
    "tagNumber",
    "en2uwnjgxodjhogi",
    "value hex must be even length: n=",
    "setBit",
    "Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.",
    "navigator.permissions.query is not a function",
    "removeChild",
    "webkitFullscreenElement",
    "getPEMStringFromHex",
    "Nexus 7",
    "separator",
    "DERGeneralizedTime",
    "get",
    "VideotexString",
    "#ShowCookie",
    "AliApp(TB",
    "crypto",
    "Trident",
    "#advertentie",
    "selenium-ide-indicator",
    "DOMRectList",
    "TRAJAN PRO",
    "text",
    "Base64 encoding incomplete: at least 2 bits missing",
    "MSStream",
    "unused bits shall be from 0 to 7: u = ",
    "Edge",
    "devicePixelRatio",
    "12.0",
    "Copy the text below to get the debug data:\n\n```\nuserAgent: ",
    "gentime",
    "HarmonyOS",
    "Invalid tag value.",
    "Minion Pro",
    "redirect",
    "setValueHex",
    "url",
    "now",
    "mod",
    "SCRIPTINA",
    "Unsupported decode mode",
    "amp-embed[type=\"zen\"]",
    "block",
    "Letter Gothic",
    "version",
    "charCodeAt",
    "destination",
    "Menlo",
    "shiftLeft",
    "isWebview",
    "includes",
    "checked",
    "DERNumericString",
    "decryptPrivateLong",
    "disabled",
    "important",
    "#cookieconsentdiv",
    "canvas_id",
    "Franklin Gothic",
    "common2345",
    "protect",
    "setValueOidString",
    "atan",
    "this.hV is null or undefined.",
    "getHexStringValue",
    "expires",
    "onmozfullscreenchange",
    "slashesCount",
    "triangle",
    "onload",
    "Private_",
    "DateTimeFormat",
    "MS Mincho",
    "fromString",
    "modPowInt",
    "auth",
    ".ctpl-fullbanner",
    "Invalid RSA private key",
    "a[href^=\"http://click.hotlog.ru/\"]",
    "EOC is not supposed to be actual content.",
    "Google",
    "RTCPeerConnectionIceEvent",
    "stringifyUrl",
    "positions",
    "X11",
    "ops",
    "only base 10 is supported",
    "[href^=\"https://aff.sendhub.pl/\"]",
    "string",
    "HELV",
    "Weibo",
    "1.2.840.113549.1.1.1",
    "GET",
    "-apple-system-body",
    "UTC",
    "decode",
    "A key was already set, overriding existing.",
    ".appguide-wrap[onclick*=\"bcebos.com\"]",
    "negate",
    "appVersion",
    "system-ui",
    "getString",
    "6509230ZHcIOq",
    "label",
    "Edg/",
    "cpuClass",
    "setPrivateKey",
    "oid",
    "modInt",
    "done",
    "buf",
    "__proto__",
    "application/hwepass2001.installepass2001",
    "addEventListener",
    "ratio",
    "5.0",
    "#bannerfloat22",
    "body",
    "ontouchstart",
    "Haettenschweiler",
    "userAgent",
    "millerRabin",
    ".boxstartwerbung",
    "ftp:",
    "MSCSSMatrix",
    "Invalid string. Length must be a multiple of 4",
    "replace",
    "utf-8",
    "_f6e3e4150",
    "nowrap",
    "#navbar_notice_50",
    "arrayFormat",
    "Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.",
    "key of param shall be only one.",
    "bin",
    "then",
    "a[href^=\"http://www.hw-area.com/?dp=\"]",
    "LN2",
    "a[title^=\"Like us on Facebook\"]",
    "decodeLength",
    "fullscreenElement",
    "REAL",
    "a[href^=\"https://ya-distrib.ru/r/\"]",
    "webkitResolveLocalFileSystemURL",
    ".widget-feedburner-counter",
    "Object",
    "MiuiBrowser",
    "oncomplete",
    ".bannergroup_werbung",
    "random",
    ".sklik",
    "denied",
    "showModalDialog",
    "Calibri",
    "a[title=\"7naga poker\" i]",
    "UCWEB",
    "href",
    "BaiduHD",
    "Futura Bk BT",
    "Pad",
    "SET",
    ".adstekst",
    "pow",
    "DERPrintableString",
    ".5px dotted transparent",
    "max",
    "length",
    "value",
    "connection",
    "4.0",
    "http:",
    "Requesting byte offset ",
    "DERObjectIdentifier",
    " is not a constructor or null",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    "a[href^=\"https://ad.letmeads.com/\"]",
    "lShiftTo",
    "TeletexString",
    ".adblocker-root",
    ".popup-social",
    "webkitPersistentStorage",
    "rec2020",
    "mozFullScreenElement",
    "about:blank",
    "#DO_CC_PANEL",
    "contextmenu",
    "\ntimeBetweenLoadAndGet: ",
    "00000000",
    "browser",
    "throw",
    "MicroMessenger",
    "UNMASKED_RENDERER_WEBGL",
    "BIT STRINGs with unused bits cannot encapsulate.",
    "(prefers-reduced-motion: ",
    "base64",
    "devtools",
    "(inverted-colors: ",
    "sortflag",
    "https",
    "(color-gamut: ",
    "no-preference",
    "#qoo-counter",
    "amp-embed[type=\"taboola\"]",
    "fontFamily",
    "1587407oHqReh",
    "canvas",
    "hidden",
    "DERAbstractStructured",
    "header",
    "oprt",
    "getPrivateBaseKey",
    "deviceMemory",
    "username",
    "__zGN8gK3T",
    "setString",
    "parseBitString",
    "img[alt=\"Hostingas Serveriai.lt\"]",
    "top",
    "getEncodedHex",
    "a[href*=\".aflam.info\"]",
    "posContent",
    "substring",
    "none",
    "browserType",
    "QQBrowser",
    "Batang",
    "ASN1Util",
    "setProperty",
    "RENDERER",
    "#ad-p3",
    "Message too long for RSA",
    "responseText",
    "jsonToASN1HEX",
    "iOS",
    "encryptPublicLong",
    "#piao_div_0[style*=\"width:140px;\"]",
    "catch",
    "map",
    " on a stream of length ",
    "Unsupported encode mode",
    ".alert-info[data-block-track*=\"CookieNotice\"]",
    "(max-monochrome: ",
    "Lucida Sans",
    "error",
    "bind",
    "coc_coc_browser",
    "a[href^=\"//afftrk.altex.ro/Counter/Click\"]",
    ".ads_rechts",
    "fogq4n2exnzc0otg",
    "hexDigits",
    "Application_",
    "parsePropertiesFrom",
    "parseOctetString",
    "ihmzq1nmrhy2m5mt",
    "chunkSize",
    "setAttribute",
    "#ads-google-middle_rectangle-group",
    "EUROSTILE",
    "dblclick",
    "responseAccessorGet",
    "SourceBufferType",
    "class",
    "8.7",
    "Blink",
    "charAt",
    "article.category-samarbete",
    "oidHexToInt",
    "date",
    "parseStringISO",
    "trimLeft",
    "a[href^=\"http://www.rssad.jp/\"]",
    "VERSION",
    "query",
    "break",
    ".as-oil",
    "Serifa",
    "array",
    "invDigit",
    "Set",
    "\\$1",
    "A[href*=\"ad.netmedia.hu\"]",
    "browserLanguage",
    "divRemTo",
    "propertyIsEnumerable",
    "Agency FB",
    "matchMedia",
    "DERTeletexString",
    "DIV.agores300",
    "freeze",
    "listen",
    "KHTML/",
    "Counter",
    "#Kolom-Iklan-728",
    "Unexpected syntax '",
    "A[href*=\"http://pay4results24.eu\"]",
    "running",
    "a[href*=\"weborama.fr/fcgi-bin/\"]",
    "mt2",
    "\n```",
    "A[href^=\"/framework/resources/forms/ads.aspx\"]",
    "getLengthHexFromValue",
    "reset",
    "message",
    "toDataURL",
    "NULL",
    ".cc5278_banner_ad",
    "adblock2345",
    ".zonepub",
    "[class*=\"_adLeaderboard\"]",
    "SNEBUY-APP",
    "a[href^=\"https://xltube.nl/click/\"]",
    "offsetParent",
    "getMinutes",
    "OID",
    "9.1",
    "whiteSpace",
    "dAddOffset",
    "a[href*=macau-uta-popup]",
    "div",
    "stop",
    "octstr",
    "hexDump",
    "openDatabase",
    "2345chrome",
    "SEQUENCE",
    "undefined key: ",
    "cosh",
    "pos",
    "createOscillator",
    "(prefers-color-scheme: dark)",
    "UTF8String",
    "encode",
    "startRendering",
    "slice",
    ".etsy-tweet",
    "Qiyu",
    "safari",
    "nextBytes",
    "not",
    "ascii",
    "valueOf",
    "navigator.deviceMemory is undefined",
    "exec",
    "NumericString",
    "ignoreBOM",
    "detect",
    "cli_priv_key",
    " byte)\n",
    "modPow",
    "tanh",
    "and",
    "expm1",
    "Apple",
    "clamp",
    "encoding",
    "#cemp_doboz",
    "MediaQueryList.matches is undefined",
    "availWidth",
    "localStorage",
    "setByASN1ObjectArray",
    "testBit",
    "Presto",
    "pathname",
    "13.0",
    "com.douban.frodo",
    "LBBROWSER",
    "localDateToUTC",
    "RIM",
    "a[href^=\"https://www.tipico.com/?affiliateId=\"]",
    "TABLE.advright",
    ".hs-sosyal",
    "acos",
    "yandex",
    ".kadr",
    "detachEvent",
    "cookie",
    "ws:",
    "drShiftTo",
    "bool",
    "__crWeb",
    "\ncomponents: ",
    "VivoBrowser",
    "parentNode",
    "obj",
    "parseUrl",
    "Arora",
    "(forced-colors: ",
    "a[href^=\"https://blackfridaysales.ro/trk/shop/\"]",
    "setPublicKey",
    "a[href^=\"https://adserver.html.it/\"]",
    "ia5str",
    "permission",
    "defineProperty",
    "attributes",
    "stack",
    "{}.constructor(\"return this\")( )",
    "osVersion",
    "28543768eIIULG",
    "Mobi",
    "TextEncoder",
    "botName",
    "iframe",
    "createElement",
    "isASCII",
    "0001",
    "exitFullscreen",
    "suspended",
    "#divAgahi",
    "Chrome OS",
    "img[alt=\"Reklaminis skydelis\"]",
    "GOTHAM",
    "intValue",
    "msSaveBlob",
    "#ad-after",
    "state",
    "application/mozilla-npqihooquicklogin",
    "wss:",
    "WEBGL_debug_renderer_info",
    "display",
    "DOM blockers debug:\n```",
    "Expected `encodedURI` to be of type `string`, got `",
    "getOwnPropertySymbols",
    "#SidebarIklan-wrapper",
    "webdriver",
    "forEach",
    "tnmq3mzbjntaxn2q",
    "RegExp out of sync",
    "5.3",
    "#ea_intext_div",
    "newFalseArray",
    "EXTERNAL",
    "Focus",
    "parent",
    "anti_replay",
    "XMLHttpRequest",
    "multiply",
    "bigIntToMinTwosComplementsHex",
    "application/asx",
    "eventClickCount",
    "substr",
    "3021300906052b2403020105000414",
    "iPad",
    "sessionStorage",
    "fragmentIdentifier",
    "addedNodes",
    "PMingLiU",
    "webkitOfflineAudioContext",
    "withMillis",
    "GraphicString",
    "device",
    "start",
    "explicit",
    ",length:",
    "stream",
    "__gCrWeb",
    "getRandomValues",
    "a[href=\"http://www.salidzini.lv/\"][style=\"display: block; width: 120px; height: 40px; overflow: hidden; position: relative;\"]",
    "colorDepth",
    "monospace",
    "sub",
    "msPointerEnabled",
    "offsetWidth",
    "mulAdd",
    "application/vnd.chromium.remoting-viewer",
    ".feedburnerFeedBlock",
    "exp",
    "BOOLEAN",
    "getContext",
    "BotdError",
    "hexByte",
    "SharedWorker",
    "strict",
    "width",
    "Reflect",
    "A[href*=\"http://axiabanners.exodus.gr/\"]",
    "type",
    "fromNumber",
    "3020300c06082a864886f70d020205000410",
    "function",
    "Arabic Typesetting",
    "add",
    "div.logly-lift-adz",
    "#ad-zone-2",
    "buffer",
    ".ModuleTemplateCookieIndicator",
    "bigint",
    "equals",
    "KHTML",
    "webkit",
    "Chromium",
    "newObject",
    "Suning",
    "2345Explorer",
    "getResponseHeader",
    "Illegal character at offset ",
    "0500",
    "sort",
    "isModified",
    "toHexString",
    "posStart",
    "fromCharCode",
    "tan",
    "divide",
    "release",
    "Opera",
    "A[href*=\"daserver.ultraweb.hu\"]",
    "msMaxTouchPoints",
    ",v=",
    "wordwrap",
    "getFullYear",
    "visibility",
    "Mb2345Browser",
    ".werbung-skyscraper2",
    "plugins",
    "OCTET_STRING",
    "cookietest=1; SameSite=Strict; expires=Thu, 01-Jan-1970 00:00:01 GMT",
    "Quark",
    "mmMwWLliI0fiflO&1",
    "puffinDevice",
    "iterator",
    "AliApp(AP",
    "') is invalid.",
    "rwNmOdr",
    "window.devicePixelRatio is undefined",
    "5.9",
    "OBJECT_IDENTIFIER",
    "asin",
    "#queTooltip",
    "active",
    "TouchEvent",
    "MediaSource",
    "application/gameplugin",
    "skipEmptyString",
    "WebKitMediaKeys",
    "extractProtocol",
    "11.0",
    "Class extends value ",
    ".ads300s",
    "BIT_STRING",
    "Clarendon",
    "isEven",
    "isNaN",
    "NET CLR",
    "appendChild",
    ".quangcao",
    "style",
    "wxwork/",
    "[title=\"Subscribe to our blog\"]",
    "childList",
    "audio_id",
    "ZWAdobeF",
    "\nfingerprintId: ",
    "keys",
    "fromInt",
    "appName",
    "Microsoft Uighur",
    "navigator.connection is undefined",
    "attack",
    "HUAWEI/",
    "request",
    "wss",
    "serializer",
    "Tablet",
    "gcda",
    "#cookies-policy-sticky",
    "outerHeight",
    "default_public_exponent",
    "A[href*=\"/hth107.com/\"]",
    "[object Array]",
    "Module",
    "dlShiftTo",
    "number",
    "mouseClick",
    "ObjectDescriptor",
    "toUpperCase",
    "setByBinaryString",
    "fromByteArray",
    "302d300d06096086480165030402040500041c",
    "bitLength",
    "#kauli_yad_1",
    "enc",
    "numstr",
    "outerWidth",
    "open",
    "audio",
    "src",
    "#onlajny-stickers",
    "a[href^=\"https://app.readpeak.com/ads\"]",
    "(prefers-contrast: ",
    "UniversalString",
    "Iceweasel",
    "9.0",
    "audioId",
    "undefined",
    "https:",
    "Windows Phone",
    "samsungAr",
    "dmp1",
    ".open.pushModal",
    "EdgeHTML",
    " elem)",
    "%C2",
    "buildID",
    "isUniversal",
    "ELEMENT_NODE",
    "setHexValueIncludingUnusedBits",
    " UBrowser",
    "less",
    "log1p",
    "DERUTCTime",
    "origin",
    "int",
    "getHours",
    "browserEngine",
    "ZERO",
    "getMonth",
    "textSizeAdjust",
    "asn1Object",
    "apply",
    "bitwiseTo",
    "false",
    "a[href*=\"/clickthrgh.asp?\"]",
    "IA5String",
    "Map",
    "coeff",
    "MT Extra",
    "posEnd",
    "fatal",
    "webkitRequestFullscreen",
    "gopher",
    "getSeconds",
    "doPublic",
    "QupZilla",
    "contentWindow",
    "Maxthon",
    "splice",
    "div[data-widget_id=\"ml6EJ074\"]",
    "Lunascape",
    "Epiphany",
    "push",
    "parse",
    ".frontpageAdvM",
    "setStringHex",
    "MeeGo",
    "div#skapiec_ad",
    "replaceState",
    "BIDUBrowser",
    "#ad-fullbanner2",
    "filter",
    "PrintableString",
    "verify",
    "Android",
    "OPR",
    "getPublicKeyB64",
    "height",
    "true",
    "hex",
    ".o--cookies--container",
    "requestIdleCallback",
    "changeBit",
    "#adblock-honeypot",
    "Content-Type",
    "oscpu",
    "readyState",
    "a[href*=\"//utimg.ru/\"]",
    "#feedback-tab",
    "Firefox",
    "a[href*=\"dubizzle.com/ar/?utm_source=\"]",
    "low",
    "[object FormData]",
    "onloadAccessor",
    "setKey",
    "#ceneo-placeholder-ceneo-12",
    "msIndexedDB",
    "responseXMLAccessorGet",
    "td#freenet_table_ads",
    "3535968sBuTTc",
    "object",
    "#mgid_iframe1",
    "selected",
    "@@iterator",
    "nodeName",
    "availLeft",
    "#vipAdmarktBannerBlock",
    "errorTrace signal unexpected behaviour",
    "acosh",
    "default",
    "doPrivate",
    "load",
    "360EE",
    "border",
    "left",
    "Helvetica Neue",
    "modInverse",
    "DEREnumerated",
    "events",
    "Macintosh",
    "#quangcaomb",
    "DEROctetString",
    "x509",
    "flipBit",
    "webgl",
    "forced",
    "DERSet",
    "Failed to decode: the 'stream' option is unsupported.",
    "simplify",
    "gcd",
    "%[a-f0-9]{2}",
    "__yb",
    "host",
    "Kindle",
    "[object Function]",
    "getPrototypeOf",
    "isEOC",
    "Failed to encode: the 'stream' option is unsupported.",
    "callback",
    "-----BEGIN RSA PRIVATE KEY-----\n",
    " UTC",
    "analyseEvent",
    "onerror",
    ".optimonk-iframe-container",
    "MS UI Gothic",
    "9.9",
    "-----BEGIN PUBLIC KEY-----\n",
    "renderedBuffer",
    "setRequestHeader",
    "BMPString",
    "#issuem-leaky-paywall-articles-zero-remaining-nag",
    "radio",
    "gw_pub_key",
    "bracket",
    "getOwnPropertyDescriptor",
    "utf8str",
    "div[id^=\"smi2adblock\"]",
    "TextDecoder",
    "create",
    "a[href*=\"booraq.org\"]",
    "constructor",
    "A[href*=\"ad.eval.hu\"]",
    ".BetterJsPopOverlay",
    "getPublicBaseKey",
    "next",
    "DERBoolean",
    "3.2.1",
    "text/html",
    "sign",
    "(no elem)",
    "-----END PUBLIC KEY-----",
    "setValueName",
    "onmousemove",
    "rShiftTo",
    "indexOf",
    "asinh",
    "multiplyLowerTo",
    "WechatWork",
    "FxiOS",
    "hasOwnProperty",
    "setPrototypeOf",
    "isProbablePrime",
    "setUnusedBitsAndHexValue",
    "enum",
    "10.0",
    "test",
    "sans-serif",
    ",sub:",
    "getPrivateKeyB64",
    "isArray",
    "application/360softmgrplugin",
    "bitCount",
    "meta[name='xxx']",
    "Baidu",
    "components",
    "protocol",
    "CrOS",
    "target",
    "byteLength",
    "sans-serif-thin",
    "loaded",
    "a[href^=\"https://affiliazioniads.snai.it/\"]",
    "from",
    "DERIA5String",
    "sqrt",
    "Notification",
    "toStringTag",
    "http",
    "DERNull",
    "getBoundingClientRect",
    "sent",
    "sortFlag",
    "serif",
    "GeneralizedTime",
    "extend",
    "match",
    "baidubrowser",
    "webkitSpeechGrammar",
    "min",
    "a[href*=\"casinopro.se\"][target=\"_blank\"]",
    "[href^=\"http://ads.glispa.com/\"]",
    "Too high value",
    "WEBGL_debug_renderer_info extension is null",
    "all",
    "webkitTextSizeAdjust",
    "__esModule",
    "#adbody",
    "Intl",
    "dmq1",
    "mozInnerScreenX",
    "#xenium_hot_offers",
    ".yandex-rtb-block",
    "9306570sYnQvQ",
    "#Publicidade",
    "setByBooleanArray",
    ".incomplete",
    "name",
    "FreeBSD",
    "set",
    "asn1",
    "getPublicBaseKeyB64",
    "6.3",
    "encrypt",
    "availHeight",
    "typeName",
    "msFullscreenElement",
    "MacIntel",
    "#semilo-lrectangle",
    "__edgeTrackingPreventionStatistics",
    "warn",
    "Debian",
    "userLanguage",
    "3021300906052b0e03021a05000414",
    "getParameter",
    "shift",
    "amp-auto-ads",
    "resolvedOptions",
    "MS Outlook",
    ".td-tags-and-social-wrapper-box",
    "atanh",
    "console",
    "getMilliseconds",
    "#social-tools",
    "(.{1,",
    "a[href^=\"http://www.trizer.pl/?utm_source\"]",
    "skipNull",
    "debugger_proof",
    "Wechat",
    "Marlett",
    "Arguments",
    "Generator is already executing.",
    "WebKit",
    "a[href^=\"http://promo.vador.com/\"]",
    "nonceToken parse error",
    "POST",
    "offsetHeight",
    "#N-ad-article-rightRail-1",
    "#CoockiesPage",
    "xhnjc3odeyndrhmj",
    "password",
    "DERTaggedObject",
    "telstr",
    "getPublicKey",
    "zeroPadding",
    "QHBrowser",
    "tagConstructed",
    "parseNumbers",
    "a[href^=\"http://www.installads.net/\"]",
    "str",
    "uris",
    "setPrivate",
    "DERAbstractString",
    "#mod-social-share-2",
    "[href^=\"https://r88.vn/\"]",
    ".sponsorit",
    "getValueHex",
    "call",
    "UCShellJava",
    "getStorageUpdates",
    "concat",
    "setASN1Object",
    "parseInteger",
    "document",
    "createDynamicsCompressor",
    "rdmje1ymjkyzrknj",
    "SeleniumIDE",
    "Silk/",
    "Firefox Focus",
    "append",
    "addTo",
    "setByDate",
    "arrayFormatSeparator",
    "file:",
    "subTo",
    "getExtension",
    "DERUTF8String",
    "send",
    "engine",
    "attachEvent",
    "Lucida Bright",
    "SeaMonkey",
    "delayFallback",
    "Levenim MT",
    "ucweb",
    "exports",
    "#ad_300X250",
    "reduce",
    "Century Gothic",
    "multiplyTo",
    "ARNO PRO",
    "EMBEDDED_PDV",
    "location",
    "toRadix",
    "a[href*=\"//playdsb.com/kr\"]",
    " (constructed)",
    "2302608PbjBgf",
    "#inlineShare",
    "#pgeldiz",
    "DERAbstractTime",
    "EOC",
    "3796767YkUQAW",
    "tag",
    "platform",
    "#adcontainer_recherche",
    "#Ads_google_02",
    "360SE",
    "textContent",
    "2000",
    "divideAndRemainder",
    "hostname",
    "mimeTypes",
    "RTCEncodedAudioFrame",
    "chrome",
    "revokeObjectURL",
    "div.holidAds",
    "a[href*=\".yabovip2027.com/\"]",
    "isCenter",
    "#taboola-below-article",
    "#Iklan-Melayang",
    "0123456789abcdefghijklmnopqrstuvwxyz",
    "[header:",
    "search",
    "extract",
    "Mobile",
    "Linux",
    "mutationObserver",
    "hTLV",
    "a[href^=\"http://www.eis.de/index.phtml?refid=\"]",
    "#publiEspecial",
    "parseStringBMP",
    ".werbung3",
    "[]=",
    "getDate",
    "xor",
    "6.5",
    "convert",
    "Failed to construct 'TextDecoder': the 'fatal' option is unsupported.",
    "abs",
    "Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.",
    "a[href^=\"https://go.alvexo.com/\"]",
    "decrypt"
];
a0_0x271d = function(_0x23dda2, _0x46f270) {
    _0x23dda2 = _0x23dda2 - 0xa2;
    var _0x3e6be8 = _0x4536c5[_0x23dda2];
    return _0x3e6be8;
}
function fromByteArray(byteArray) {
  return Buffer.from(byteArray).toString('base64');
}

function _0x2f41b5(_0x11873c, _0x590c52) {
    var _0x22d5b4 = a0_0x271d, _0x119353, _0x4d44d3;
    if (void 0x0 === _0x590c52 && (_0x590c52 = _0x22d5b4(0x247)),
    'string' != typeof _0x11873c)
        return _0x11873c;
    var _0x5a18ae = (_0x119353 = new TextEncoder()[_0x22d5b4(0x2d0)](_0x11873c))[_0x22d5b4(0x22b)] + 0x4 + 0x1;
    console.log(_0x5a18ae)
    _0x4d44d3 = new Uint8Array(new ArrayBuffer(_0x5a18ae));
    for (var _0x4d24a4 = 0x38, _0x5099bf = 0x0, _0x36404e = 0x0; _0x36404e < 0x3; _0x36404e++)
        _0x4d44d3[_0x5099bf] = Math[_0x22d5b4(0x10b)](0xa * Math[_0x22d5b4(0x21a)]()),
        _0x4d24a4 ^= _0x4d44d3[_0x5099bf],
        _0x5099bf++;
    _0x4d44d3[_0x5099bf] = 0x3f ^ _0x4d44d3[0x1],
    _0x4d24a4 ^= _0x4d44d3[_0x5099bf],
    _0x5099bf++;
    for (var _0x47892e = 0x0; _0x47892e < _0x119353['length']; _0x47892e++)
        _0x4d24a4 ^= _0x119353[_0x47892e],
        _0x4d44d3[_0x5099bf++] = _0x119353[_0x47892e] ^ _0x4d44d3[_0x47892e % 0x3] ^ 0x65 ^ _0x47892e + _0x4d44d3[0x0];
    _0x4d44d3[_0x5099bf] = _0x4d24a4;
    var _0x4642e3 = '';
    if (_0x22d5b4(0x247) === _0x590c52)
        _0x4642e3 = fromByteArray(_0x4d44d3);
    else {
        if (_0x22d5b4(0x2d8) !== _0x590c52)
            throw new Error(_0x22d5b4(0x274));
        _0x4642e3 = new window[(_0x22d5b4(0x463))]()[_0x22d5b4(0x1e4)](_0x4d44d3);
    }
    return _0x4642e3;
}


param = 'event_status=&event_type=&isSearch=false&page=5&page_size=20&search='
console.log(_0x2f41b5(param, 'base64'))
